#specifies Events, Jobs,Runners, Steps, Actions
# Event- trigger for a workflow
# 
name: Cypress Tests

#Trigger - pushed to repo  
on:
  push:
    #branches: [ "master" ]
    # paths:
  #pull_request:
    #branches: [ "master" ]
    paths:
      '.github/workflows/cypress.yaml'

  workflow_dispatch:

env:
  workingDirectory: ./easy-note

jobs:
  set-up:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}/${{ env.workingDirectory }}

    # Checks repo, pulls in the pipeline 
    steps:
    - name: Checkout 
      uses: actions/checkout@v3

    - name: Log
      run: | 
        echo ${{ github.workspace }};
        echo ${{ env.workingDirectory }}
        echo ls;

     # Sets up Node
    - name: Use Node 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: yarn --cwd ./easy-note/ install

    # Installs our dependencies
    - name: Cypress run 
      uses: cypress-io/github-action@v3
      with:
        #repository: itech-it1i-gruppe6/EasyNote/easy-note
        #repo-token: ${{ secrets.GITHUB_TOKEN }}
        #path: /home/runner/work/EasyNote/EasyNote/easy-note
        start: yarn start
        project: ./easy-note
        build: yarn  build
        install: true
        

      
  




